# Exported from Render on 2024-07-08T14:13:26Z
services:
- type: web
  name: mysite
  runtime: ruby
  repo: https://github.com/Data-Khan1/Plagiarism-Detector
  plan: free
  envVars:
  - key: WEB_CONCURRENCY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
